---
version: 2
project_name: wt
archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    files:
      - LICENSE
      - README.md
      - third_party_licenses/**/*
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
builds:
  - binary: wt
    main: cmd/wt/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
release:
  prerelease: "true"
  header: |
    [Pull Requests](https://github.com/suzuki-shunsuke/wt/pulls?q=is%3Apr+milestone%3A{{.Tag}}) | [Issues](https://github.com/suzuki-shunsuke/wt/issues?q=is%3Aissue+milestone%3A{{.Tag}}) | https://github.com/suzuki-shunsuke/wt/compare/{{.PreviousTag}}...{{.Tag}}

sboms:
  - id: default
    disable: false
